### ISSUE TITLE
How to use this code?

### ISSUE THREAD

**Issue by Roy-Kid** [manie204/mpidb#1]
Hi, your idea is brilliant, but I have some problems when I use it.
First, when I use `mpirun -np 4 mpidb mpi_app` to launch, then then terminal blocked at `listening on port 13372`. Then how do I debug it (gdb or vscode). When I use gdb to attach the pid, it says it already be traced. 

Second, if I want to use `mpirun -n 8 -- mpidb mpi_app | mpidbc vscode launch.json`, which file is the "mpidbc" specify for, `mpidbc.py` under `tools/mpidbc`? (To my understanding, the mpidbc will generate a launch.json then replace the one under .vscode.)

I think this is a good tools to debug mpi, hope we can dev it in the future!

**Comment by Roy-Kid** [comment]
Hi, I find out how to use gdbserver, it can use `target remote host:port` in gdb command-line. And when I want to use vscode to debug the program, the following error raise: 
![image](https://user-images.githubusercontent.com/42854324/119919463-164f5280-bf9d-11eb-9d1e-cc3c65637382.png)
![image](https://user-images.githubusercontent.com/42854324/119919486-2404d800-bf9d-11eb-9731-85be570dbe5e.png)
Please help me how to fix this if you are convenient! Thanks a lot!

**Comment by mystery-e204** [comment]
Hi,

First of all, thanks for showing interest in this project and I'm terribly sorry that I didn't respond earlier. I have been awfully busy these past weeks and thus haven't checked github at all. If you are still interested in using this debugging solution and still have any questions, I'd be happy to answer them now.

Regarding your second post, I'm not entirely sure what's going on there, so I would need to know a bit more of what you do exactly (which commands you run, what the launch.json file looks like, etc.).

**Comment by Roy-Kid** [comment]
Hi, thanks for your reply! I have changed the work and don't work for MPI for a while. I will give you more detailed information after I set up my env again! I do like your idea of the code, hope one day I can contribute to it!
